# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftUI2.0-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftUI2.0-Example
  pod 'WaterfallGrid', '~> 1.0.0'

end
